// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnOvZ84IxueXFMrZkViHPMWTue-bigW8',
    appId: '1:955026876669:android:e087c1bd12b661a2d13694',
    messagingSenderId: '955026876669',
    projectId: 'chatfl-251ec',
    storageBucket: 'chatfl-251ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAHMg-Uy3WfEs6S8VyCgxNh6SdjQTyvw',
    appId: '1:955026876669:ios:a2344c6bf150dfbfd13694',
    messagingSenderId: '955026876669',
    projectId: 'chatfl-251ec',
    storageBucket: 'chatfl-251ec.appspot.com',
    androidClientId: '955026876669-kgl26h97kdrrgsaj2qcsm2tn4rsppm73.apps.googleusercontent.com',
    iosClientId: '955026876669-o5aev4m1c7epenjnjkfk3cmuu2kue8do.apps.googleusercontent.com',
    iosBundleId: 'thexarcano.com.chat2',
  );
}
